name: flutter_osk_x
description: A package to show/hide virtual keyboard on windows 10.
version: 0.1.0
homepage: https://github.com/ekasetiawans/flutter_osk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  win32: ^3.1.3
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
